#!/bin/bash
url="https://sourceforge.net/projects/check"
new1="Check "
new2="<a"
downcommand="wget -q" 
pushd $(dirname $0) > /dev/null
rm -f index.html && $downcommand "$url" -O index.html
if [ -f index.html ];then
	newver=$(cat index.html |grep "Check .*<a"|head -n 1|sed -e 's/^.*Check //g'|sed -e 's/ <a.*$//g')
	echo $newver
else
	echo "不能正常取得新版本号"
	exit 1
fi
rm -f index.html
popd > /dev/null
