# Generated from scruffy-0.2.6.gem by gem2rpm -*- rpm-spec -*-
%global gem_name scruffy

Summary: A powerful, clean graphing library for Ruby
Name: rubygem-%{gem_name}
Version: 0.3.0
Release: 8.beta1%{?dist}
Group: Development/Languages
License: MIT
URL: https://github.com/brasten/scruffy
Source0: http://rubygems.org/gems/%{gem_name}-%{version}.beta1.gem
Patch0: relax-builder-dep-in-gemspec.patch
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
Requires: ruby(rubygems)
Requires: ruby(release)
Requires: rubygem(builder) >= 2.0
BuildRequires: ruby(rubygems)
BuildRequires: rubygems-devel
BuildRequires: rubygem(builder)
BuildRequires: rubygem(minitest)
BuildRequires: rubygem(rspec)
BuildRequires: ruby-RMagick
BuildArch: noarch
Provides: rubygem(%{gem_name}) = %{version}

%description
Scruffy is a Ruby library for generating high quality, good looking graphs. It
is designed to be easy to use and highly customizable.

%package doc
Summary: Scruffy gem documentation
License: MIT and CC-BY and LGPLv2+

%description doc
Documentation for rubygem-scruffy

%prep
%setup -q -c -T
%gem_install -n %{SOURCE0}

pushd .%{gem_dir}/specifications
%patch0 -p0
rm %{gem_name}-%{version}.beta1.gemspec.orig
popd

%build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* %{buildroot}%{gem_dir}

%check
pushd .%{gem_instdir}.beta1
rspec spec
popd

%files
%defattr(-, root, root, -)
%dir %{gem_instdir}.beta1
%{gem_instdir}.beta1/lib
%doc %{gem_instdir}.beta1/CHANGES.txt
%doc %{gem_instdir}.beta1/README.txt
%{gem_dir}/cache/%{gem_name}-%{version}.beta1.gem
%{gem_dir}/specifications/%{gem_name}-%{version}.beta1.gemspec

%files doc
%defattr(-,root,root,-)
%doc %{gem_instdir}.beta1/spec
%doc %{gem_dir}/doc/%{gem_name}-%{version}.beta1

%changelog
* Thu Jun 18 2015 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 0.3.0-8.beta1
- Rebuilt for https://fedoraproject.org/wiki/Fedora_23_Mass_Rebuild

* Fri Jun 27 2014 Mo Morsi <mmorsi@redhat.com> - 0.3.0-7.beta1
- rm backup generated by patch command

* Sun Jun 08 2014 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 0.3.0-6.beta1
- Rebuilt for https://fedoraproject.org/wiki/Fedora_21_Mass_Rebuild

* Sun Aug 04 2013 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 0.3.0-5.beta1
- Rebuilt for https://fedoraproject.org/wiki/Fedora_20_Mass_Rebuild

* Mon Mar 11 2013 Vít Ondruch <vondruch@redhat.com> - 0.3.0-4.beta1
- Rebuild for https://fedoraproject.org/wiki/Features/Ruby_2.0.0

* Thu Feb 14 2013 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 0.3.0-3.beta1
- Rebuilt for https://fedoraproject.org/wiki/Fedora_19_Mass_Rebuild

* Tue Jul 17 2012 Mo Morsi <mmorsi@redhat.com> - 0.3.0-2.beta1
- added patch0 relaxing builder dependency

* Mon Feb 13 2012 Mo Morsi <mmorsi@redhat.com> - 0.3.0-1.beta1
- updated to latest upstream release for various fixes
- updated to ruby 1.9

* Sat Jan 14 2012 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 0.2.6-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_17_Mass_Rebuild

* Thu Dec 15 2011 Vít Ondruch <vondruch@redhat.com> - 0.2.6-5
- Migrated to RSpec 2.x.

* Mon Aug 08 2011 Mo Morsi <mmorsi@redhat.com> - 0.2.6-4
- Replace BR(check) with BR

* Wed Feb 09 2011 Fedora Release Engineering <rel-eng@lists.fedoraproject.org>
- Rebuilt for https://fedoraproject.org/wiki/Fedora_15_Mass_Rebuild

* Tue Aug 10 2010 Mohammed Morsi <mmorsi@redhat.com> - 0.2.6-2
- Updates based on feedback
- Created seperate doc package for docs

* Tue Aug 03 2010 Mohammed Morsi <mmorsi@redhat.com> - 0.2.6-1
- Initial package
