#!/bin/bash
url="http://gondor.apana.org.au/~herbert/dash/files/?C=M&O=D"
new1="dash-"
new2=".tar.gz"
downcommand="wget -q" 
pushd $(dirname $0) > /dev/null
rm -f index.html && lftp -c "open ftp://invisible-island.net/diffstat/;ls -t" > index.html
if [ -f index.html ];then
	newver=`cat index.html |grep "^.*diffstat-.*.tgz" | head -n 1| sed "s/.*diffstat-//" | sed "s/.tgz.*$//" |sed "s/-/./"`
	echo $newver
else
	echo "不能正常取得新版本号"
	exit 1
fi
rm -f index.html
popd > /dev/null
