#!/bin/bash
if [ -z "$1" ] ; then
        echo "使用方法：$0 新版本号"
        exit 1
fi
pushd $(dirname $0)
sed -i "s/Version:.*/Version:\t$1/g" libxkbcommon.spec
sed -i "s/Release:.*/Release: 1%{?gitdate:.%{gitdate}}%{?dist}/g" libxkbcommon.spec
popd
