Name:           perl-HTTP-OAI
Version:        3.27
Release:        5%{?dist}
Summary:        API for the OAI-PMH
License:        BSD
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/HTTP-OAI/
Source0:        http://www.cpan.org/authors/id/T/TI/TIMBRODY/HTTP-OAI-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl(CGI)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(HTTP::Request)
BuildRequires:  perl(HTTP::Response)
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(URI)
BuildRequires:  perl(XML::LibXML) >= 1.6
BuildRequires:  perl(XML::LibXML::SAX)
BuildRequires:  perl(XML::SAX)
BuildRequires:  perl(XML::SAX::Base) >= 1

%description
This is a stub module, you probably want to look at HTTP::OAI::Harvester or
HTTP::OAI::Repository.

%prep
%setup -q -n HTTP-OAI-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

iconv -f iso8859-15 -t utf-8 README > README.conv && mv -f README.conv README

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check


%files
%doc CHANGES LICENSE README
%{perl_vendorlib}/*
%{_bindir}/*
%{_mandir}/man3/*
%{_mandir}/man1/*
%changelog
* Fri Jun 13 2014 Liu Di <liudidi@gmail.com> - 3.27-5
- 为 Magic 3.0 重建

* Wed Dec 12 2012 Liu Di <liudidi@gmail.com> - 3.27-4
- 为 Magic 3.0 重建

* Sun Jan 29 2012 Liu Di <liudidi@gmail.com> - 3.27-3
- 为 Magic 3.0 重建

* Fri Jan 13 2012 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 3.27-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_17_Mass_Rebuild

* Mon Nov 28 2011 Nicholas van Oudtshoorn <vanoudt@gmail.com> - 3.27-1
- tidying of spec file
- new upstream release 3.27
* Thu Apr 28 2011 Nicholas van Oudtshoorn <vanoudt@gmail.com> - 3.24-1
- Specfile autogenerated by cpanspec 1.78.
