#!/bin/bash
if [ -z "$1" ] ; then
        echo "使用方法：$0 新版本号"
        exit 1
fi
pushd $(dirname $0)
N3=$(echo $1|cut -d"." -f3)
sed -i "s/%define stable_update.*/%define stable_update $N3/" kernel.spec
popd
