#!/bin/bash
url="https://download.gnome.org/sources/gtk+/"
new1="a href="
new2="\\/<\\/a"
downcommand="wget -q" 
pushd $(dirname $0) > /dev/null
specver=`rpmspec -q --qf "%{version}\n" gtk2.spec |head -n 1`
newver1=$(echo $specver | cut -d"." -f1).$(echo $specver | cut -d"." -f2)
rm -f index.html
url1="$url$newver1/"
$downcommand $url1 -O index.html
new3="gtk+-"
new4=".tar.xz"
if [ -f index.html ];then
	newver=`grep "$new3.*$new4" index.html |tail -n 1| sed "s/.*$new3//" | sed "s/$new4.*//" | sed 's/^[ ]\{1,\}//;s/[ ]\{1,\}$//g'`
	echo $newver
else
        echo "不能正常取得新版本号"
        exit 1
fi
rm -f index.html
popd > /dev/null
