Name:           libsexy
Version:        0.1.11
Release:        5%{?dist}
Summary:        Funky fresh graphical widgets for GTK+ 2
Summary(zh_CN.UTF-8):	一些 GTK+2 的有意思的新图形部件

Group:          System Environment/Libraries
Group(zh_CN.UTF-8):	系统环境/库
License:        LGPLv2+
URL:            http://www.chipx86.com/wiki/Libsexy
Source0:        http://releases.chipx86.com/%{name}/%{name}/%{name}-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:  gtk2-devel
BuildRequires:	libxml2-devel
BuildRequires:	iso-codes-devel
Requires:	enchant


%description
Some funky fresh graphical widgets for GTK+ 2 applications.

%description -l zh_CN.UTF-8
一些 GTK+2 的有意思的新图形部件

%package        devel
Summary:        Development files for %{name}
Summary(zh_CN.UTF-8):	%{name} 的开发文件
Group:          Development/Libraries
Group(zh_CN.UTF-8): 	开发/库
Requires:       %{name} = %{version}-%{release}
Requires:	pkgconfig
Requires:	gtk2-devel
Requires:	libxml2-devel


%description    devel
The %{name}-devel package contains libraries and header files for
developing applications that use %{name}.

%description devel -l zh_CN.UTF-8
%{name} 的开发文件

%prep
%setup -q


%build
%configure --disable-static LIBS="-lgmodule-2.0"
make %{?_smp_mflags}


%install
rm -rf $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT
find $RPM_BUILD_ROOT -name '*.la' -exec rm -f {} ';'

# Copy the files from the tarball to avoid the IDs generated by gtk-doc being
# different on different builds
mkdir -p $RPM_BUILD_ROOT%{_datadir}/gtk-doc/html/%{name}/
cp -a docs/reference/html/* $RPM_BUILD_ROOT%{_datadir}/gtk-doc/html/%{name}/
magic_rpm_clean.sh

%clean
rm -rf $RPM_BUILD_ROOT


%post -p /sbin/ldconfig


%postun -p /sbin/ldconfig


%files
%defattr(-,root,root,-)
%doc COPYING AUTHORS NEWS
%{_libdir}/%{name}.so.*


%files devel
%defattr(-,root,root,-)
%{_datadir}/gtk-doc/html/%{name}
%{_includedir}/%{name}
%{_libdir}/%{name}.so
%{_libdir}/pkgconfig/%{name}.pc


%changelog
* Fri Dec 07 2012 Liu Di <liudidi@gmail.com> - 0.1.11-5
- 为 Magic 3.0 重建

