"cmdtrack", NULL,			/* Removed from TeXLive - non-free */
"fltpage", NULL,			/* Removed from TeXLive - non-free */
"free-math-font-survey", NULL, 		/* Removed from TeXLive - non-free */
"kalender", NULL,			/* Removed from TeXLive - non-free */
"latex-tipps-und-tricks", NULL,  	/* Removed from TeXLive - non-free */
"russ", NULL,				/* Removed from TeXLive - non-free */
"preview", NULL,			/* upstream in Fedora */
"psutils", NULL,			/* in Fedora */
"floatflt", "LPPL",
"seetexk", "MIT",
"texdraw", "CC-BY",
"ogham", "Public Domain",
"midnight", "midnight",
"ec", "ec",
"setspace", "Copyright only", 		/* http://www.linux.cz/pipermail/texlive/2011-December/000357.html */
"authoraftertitle", "Public Domain", 	/* http://www.linux.cz/pipermail/texlive/2011-December/000359.html */
"gentle", "CC-BY-SA",			/* http://www.linux.cz/pipermail/texlive/2011-December/000375.html */
"gillcm", "BSD",			/* http://www.linux.cz/pipermail/texlive/2011-December/000382.html */
"doc-pictex", "Copyright only", 	/* http://www.linux.cz/pipermail/texlive/2011-December/000386.html */
"abstyles", "Abstyles",			/* http://www.linux.cz/pipermail/texlive/2011-December/000343.html */
"adobemapping", "BSD",
"ANUfinalexam", "GPL+",
"apalike2", "Knuth",
"apa6e", "BSD",
"arpic", "Arpic",
"ar", "LPPL",
"asana-math", "OFL",
"ascii-chart", "LPPL",
"bbm", "Copyright only",
"bbold-type1", "Copyright only",
"bera", "Bitstream vera",
"berenisadf", "GPLv2+ and LPPL",
"bchart", "MIT",
"blacklettert1", "LPPL",
"borceux", "Borceux",
"braille", "LPPL",
"breakcites", "Copyright only",
"calligra", "Copyright only",
"calligra-type1", "Copyright only",
"charter", "Copyright only",
"cherokee", "Copyright only",
"chicago", "Knuth",
"cite", "Copyright only",
"clock", "GPL+",
"cm-unicode", "OFL",
"codepage", "BSD",
"context-filter", "BSD",
"context-mathsets", "BSD",
"context-rst", "BSD",
"context", "GPL+ or LPPL",
"context-vim", "BSD",
"courseoutline", "Copyright only",
"coursepaper", "Copyright only",
"crossword", "Crossword",
"csplain", "GPLv2+",
"dancers", "Copyright only",
"de-macro", "AFL",
"detex", "NCSA",
"din1505", "Bibtex",
"dk-bib", "GPLv2+",
"dosepsbin", "GPLv2 or Artistic",
"dotseqn", "Dotseqn",
"doublestroke", "Doublestroke",
"dvidvi", "Copyright only",
"ecv", "Copyright only",
"eiad", "Public Domain",
"electrum", "GPLv2+ with exceptions and LPPL",
"elvish", "Elvish",
"epstopdf", "BSD",
"eqname", "Copyright only",
"esstix", "OFL",
"etex-pkg", "LPPL",
"eurosym", "Eurosym",
"facture", "CC-BY-SA",
"fancynum", "LPPL",
"fbithesis", "LPPL",
"figflow", "Copyright only",
"finbib", "Bibtex",
"fltpoint", "LPPL",
"fonetika", "GPL+ and LPPL",
"font-change", "CC-BY-SA",
"formlett", "GPL+",
"framed", "Copyright only",
"fundus", "LPPL",
"fwlw", "Copyright only",
"gene-logic", "Crossword",
"gentium", "OFL",
"germbib", "Bibtex",
"getoptk", "CeCILL-B",
"gfsartemisia", "LPPL",
"gfsbaskerville", "LPPL",
"gfsbodoni", "OFL",
"gfscomplutum", "OFL",
"gfsdidot", "LPPL",
"gfsneohellenic", "LPPL",
"gfsporson", "LPPL",
"gfssolomos", "OFL",
"harvmac", "CC-BY",
"hc", "GPLv2+",
"hyphen-basque", "Bahyph",
"hyphenex", "Public Domain",
"hyphen-greek", "LPPL",
"hyphen-turkish", "Copyright only",
"hyph-utf8", "Copyright only",
"ifsym", "LPPL",
"inconsolata", "OFL",
"index", "LPPL",
"ipaex", "IPA",
"itrans", "BSD",
"jadetex", "MIT",
"jamtimes", "BSD",
"japanese-otf", "BSD",
"jlabels", "Bibtex or LPPL",
"kixfont", "Copyright only",
"latex2e-help-texinfo", "Latex2e",
"lhcyr", "Lhcyr",
"localloc", "Bibtex",
"lshort-german", "GFDL",
"lshort-spanish", "GPLv2+",
"lshort-ukr", "GPLv2+",
"lua-alt-getopt", "MIT",
"magaz", "Copyright only",
"makeindex", "MakeIndex",
"mdputu", "BSD",
"menu", "LPPL",
"metapost-examples", "GPL+",
"mhequ", "Public Domain",
"mil3", "Copyright only",
"minutes", "LPPL",
"mkgrkindex", "LPPL",
"mkjobtexmf", "GPLv2 or Artistic",
"mpman-ru", "MIT",
"mp3d", "LPPL",
"mslapa", "Public Domain",
"mxedruli", "LPPL",
"nature", "LPPL",
"newsletr", "Newsletr",
"ocr-b-outline", "Copyright only",
"ocr-b", "Copyright only",
"oldstandard", "OFL",
"oubraces", "Copyright only",
"passivetex", "MIT",
"path", "Bibtex",
"pax", "GPLv2+",
"pb-diagram", "GPLv2+",
"persian-modern", "OFL",
"philokalia", "OFL",
"plain-doc", "Public Domain",
"plweb", "Copyright only",
"pnas2009", "Bibtex",
"prodint", "OFL",
"productbox", "Copyright only",
"psfrag", "psfrag",
"pst-bspline", "LPPL",
"ps2pkm", "MIT",
"ptex", "BSD",
"punknova", "Punknova",
"rccol", "LPPL",
"rsfs", "rsfs",
"r_und_s", "BSD",
"shapepar", "Dotseqn",
"showhyphens", "MIT",
"slideshow", "Copyright only",
"sphack", "Bibtex",
"stix", "OFL",
"subsupscripts", "LPPL",
"tabls", "Dotseqn",
"tds", "Latex2e",
"tetex", "GPL+ and GPLv2+ and LPPL",
"texdiff", "GPL+ or Artistic",
"texdirflatten", "GPL+ or Artistic",
"texloganalyser", "BSD",
"tex-refs", "GFDL",
"threeparttable", "Threeparttable",
"tie", "Latex2e",
"tikz-dependency", "(GPLv2 or LPPL) and (GFDL or LPPL)",
"tucv", "CC-BY-SA",
"tugboat-plain", "Bibtex",
"ulem", "Copyright only",
"umtypewriter", "OFL",
"utopia", "Utopia",
"venturisadf", "Utopia",
"version", "Copyright only",
"vntex", "Utopia",
"wadalab", "Wadalab",
"webguide", "Utopia",
"wsuipa", "Utopia",
"xdvi", "MIT",
"zed-csp", "Zed",
