#!/bin/bash
if [ -z "$1" ] ; then
        echo "使用方法：$0 新版本号"
        exit 1
fi
pushd $(dirname $0)
ver=$(echo $1|sed -e 's/1.9.//g')
sed -i "s/%define byaccdate.*/%define byaccdate $ver/g" byacc.spec
popd
