#!/bin/bash
url="https://download.gnome.org/sources/folks/"
new1="a href="
new2="\\/<\\/a"
downcommand="wget -q" 
pushd $(dirname $0) > /dev/null
if ! [ x"$UPDATEMAJOR" = x"" ]; then
	rm -f index.html && $downcommand $url -O index.html
	if [ -f index.html ];then
		newver1=`grep "$new1.*$new2" index.html |tail -n 1| sed "s/.*$new1//" | sed "s/$new2.*//" | sed 's/^[ ]\{1,\}//;s/[ ]\{1,\}$//g'| cut -d">" -f 2`
	else
		echo "不能正常取得新版本号"
		exit 1
	fi
else
	specver=`rpmspec -q --qf "%{version}\n" folks.spec |head -n 1`
	newver1=$(echo $specver | cut -d"." -f1).$(echo $specver | cut -d"." -f2)
fi	
rm -f index.html
url1="http://ftp.acc.umu.se/pub/GNOME/sources/folks/$newver1/?C=M&O=D"
$downcommand $url1 -O index.html
new3="folks-"
new4=".tar.xz"
if [ -f index.html ];then
	newver=`grep "$new3.*$new4" index.html |head -n 1| sed "s/.*$new3//" | sed "s/$new4.*//" | sed 's/^[ ]\{1,\}//;s/[ ]\{1,\}$//g'`
	echo $newver
else
        echo "不能正常取得新版本号"
        exit 1
fi
rm -f index.html
popd > /dev/null
