#!/bin/bash
if [ -z "$1" ] ; then
        echo "使用方法：$0 新版本号"
        exit 1
fi
pushd $(dirname $0)
MAJOR=$(echo $1|cut -f1 -d".")
MINOR=$(echo $1|cut -f2 -d".")
PATCHLEVEL=$(echo $1|cut -f3 -d".")
sed -i "s/%define major.*/%define major $MAJOR/g" gnuplot.spec
sed -i "s/%define minor.*/%define minor $MINOR/g" gnuplot.spec 
sed -i "s/%define patchlevel.*/%define patchlevel $PATCHLEVEL/g" gnuplot.spec
popd
