#!/bin/bash
if [ -z "$1" ] ; then
        echo "使用方法：$0 新版本号"
        exit 1
fi
pushd $(dirname $0)
sed -i "s/Version:.*/Version: $1/g" m17n-lib.spec
sed -i "s/Release:.*/Release: 1%{?dist}/g" m17n-lib.spec
popd
