Summary:	Tool for tunneling SSH through HTTP proxies
Summary(zh_CN.UTF-8): 通过 HTTP 代理使用 SSH 隧道的工具
Name:		corkscrew
Version:	2.0
Release:	13%{?dist}
License:	GPLv2
Group:		Applications/Internet
Group(zh_CN.UTF-8): 应用程序/互联网
URL:		http://www.agroman.net/corkscrew/
Source0:	http://www.agroman.net/corkscrew/%{name}-%{version}.tar.gz
Source1:	%{name}.1

Patch0:		%{name}-%{version}-from-debian.patch
Patch1:		%{name}-%{version}-typo.patch

BuildRoot:	%(mktemp -ud %{_tmppath}/%{name}-%{version}-%{release}-XXXXXX)

%description
Corkscrew is a tool for tunneling SSH through HTTP proxies.

It has been tested with the following HTTP proxies :
 * Gauntlet
 * CacheFlow
 * JunkBuster
 * Apache mod_proxy

%description -l zh_CN.UTF-8
通过 HTTP 代理使用 SSH 隧道的工具。

%prep
%setup -q
%patch0 -p1
%patch1 -p1

%build
%configure
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{_mandir}/man1

make install INSTALL="%{__install} -p" DESTDIR=$RPM_BUILD_ROOT

# man page
install -p -m644 %{SOURCE1} $RPM_BUILD_ROOT%{_mandir}/man1

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc AUTHORS
%doc ChangeLog
%doc COPYING
%doc README
%doc TODO
%{_bindir}/%{name}
%{_mandir}/man1/%{name}.1.gz

%changelog
* Wed Dec 05 2012 Liu Di <liudidi@gmail.com> - 2.0-13
- 为 Magic 3.0 重建

* Tue Feb 08 2011 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 2.0-11
- Rebuilt for https://fedoraproject.org/wiki/Fedora_15_Mass_Rebuild

* Fri Jul 24 2009 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 2.0-10
- Rebuilt for https://fedoraproject.org/wiki/Fedora_12_Mass_Rebuild

* Tue Feb 24 2009 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 2.0-9
- Rebuilt for https://fedoraproject.org/wiki/Fedora_11_Mass_Rebuild

* Sat Feb 09 2008 Debarshi Ray <rishi@fedoraproject.org> - 2.0-8
- Rebuilding with gcc-4.3 in Rawhide.

* Fri Nov 16 2007 Debarshi Ray <rishi@fedoraproject.org> - 2.0-7
- Fixed the value of Release according to Fedora dist tag guidelines.
- Preserved timestamps using 'install -p'.

* Fri Aug 03 2007 Debarshi Ray <rishi@fedoraproject.org> - 2.0-6
- Moved the online manual page from Patch0 to Source1.

* Fri Aug 03 2007 Debarshi Ray <rishi@fedoraproject.org> - 2.0-5
- Changed value of License according to Fedora licensing guidelines.

* Sun Jun 10 2007 Debarshi Ray <rishi@fedoraproject.org> - 2.0-4
- Removed 'export CC=gcc' from the build stanza.

* Wed Jun 06 2007 Debarshi Ray <rishi@fedoraproject.org> - 2.0-3
- Removed '[ -d $RPM_BUILD_ROOT ]' from the install stanza.
- Changed value of BuildRoot as per recommendations in Fedora packaging
  guidelines.

* Sat May 19 2007 Debarshi Ray <rishi@fedoraproject.org> - 2.0-2
- Addressed warnings generated by rpmlint, and changed Source0 into a URL.
- Added AUTHORS, ChangeLog, COPYING and TODO in the list of documentation
  files.
- Added online manual page and patches to README and corkscrew.c from Debian.
- Fixed a typo in README.

* Sat May 12 2007 Debarshi Ray <rishi@fedoraproject.org> - 2.0-1
- Initial build.
