#!/bin/bash
url=""
new1="pinentry-"
new2=".tar.bz2"
downcommand="wget -q" 
pushd $(dirname $0) > /dev/null
rm -f index.html && lftp -c "open ftp://ftp.gnupg.org/gcrypt/pinentry//;cls --sort=date" >> index.html
if [ -f index.html ];then
	newver=`grep "$new1.*$new2" index.html|head -n 1| sed "s/.*$new1//" | sed "s/$new2.*//" | sed 's/^[ ]\{1,\}//;s/[ ]\{1,\}$//g'`
	echo $newver
else
	echo "不能正常取得新版本号"
	exit 1
fi
rm -f index.html
popd > /dev/null
