#!/bin/bash
url="http://mirrors.ustc.edu.cn/fedora/linux/development/rawhide/source/SRPMS/t/"
new1="tor-"
new2="-.*"
downcommand="wget -q" 
pushd $(dirname $0) > /dev/null
rm -f index.html && $downcommand $url -O index.html
if [ -f index.html ];then
	newver=`html2text index.html|grep -v arm|grep "^tor\-"|head -n 1| sed "s/.*$new1//" | sed "s/$new2.*//" | sed 's/^[ ]\{1,\}//;s/[ ]\{1,\}$//g'`
	echo $newver
else
	echo "不能正常取得新版本号"
	exit 1
fi
rm -f index.html
popd > /dev/null
