#!/bin/bash
url="http://thrysoee.dk/editline/"
new1="libedit-"
new2=".tar.gz"
downcommand="wget -q" 
pushd $(dirname $0) > /dev/null
rm -f index.html && $downcommand "$url" -O index.html
if [ -f index.html ];then
	newver=`grep "$new1.*$new2" index.html|head -n 1| sed "s/.*$new1//" | sed "s/$new2.*//" | sed 's/^[ ]\{1,\}//;s/[ ]\{1,\}$//g'`
	newver1=`echo $newver|cut -d"-" -f1`
	newver2=`echo $newver|cut -d"-" -f2`
	echo $newver2.$newver1
else
	echo "不能正常取得新版本号"
	exit 1
fi
rm -f index.html
popd > /dev/null
