#!/bin/bash
if [ -z "$1" ] ; then
        echo "使用方法：$0 新版本号"
        exit 1
fi
pushd $(dirname $0)
sed -i "s/Version:.*/Version: $1/g" cfitsio.spec
tarver=$(echo $1|sed -e 's/\.//g')
sed -i "s/%define tarversion.*/%define tarversion $tarver/g" cfitiso.spec
popd
