#!/bin/bash
url="http://mirrors.ustc.edu.cn/kde/stable/applications/"
downcommand="wget -q" 
pushd $(dirname $0) > /dev/null
rm -f index.html && $downcommand "$url" -O index.html
if [ -f index.html ];then
	newver=`grep "15\.[0-9}\+\.[0-9]\+" index.html -o |tail -n 1`
	echo $newver
else
	echo "不能正常取得新版本号"
	exit 1
fi
rm -f index.html
popd > /dev/null
