#!/bin/bash
if [ -z "$1" ] ; then
        echo "使用方法：$0 新版本号"
        exit 1
fi
pushd $(dirname $0)
crdaver=$(echo $1|cut -d"_" -f1)
regdbver=$(echo $1|cut -d"_" -f2)
#sed -i "s/Version:.*/Version:\t$1/g" crda.spec
sed -i "s/%define         crda_version.*/%define         crda_version    $crdaver/g" crda.spec
sed -i "s/%define         regdb_version.*/%define         regdb_version   $regdbver/g" crda.spec
popd
