#!/bin/sh

# Source system prefs
if [ -f /etc/java/maven.conf ] ; then
  . /etc/java/maven.conf
fi

# Source user prefs
if [ -f $HOME/.mavenrc ] ; then
  . $HOME/.mavenrc
fi

if [ -f /usr/share/java-utils/java-functions ] ; then
  . /usr/share/java-utils/java-functions
  set_jvm
  set_javacmd
fi

export M2_HOME="${M2_HOME:-/usr/share/maven}"
export JAVA_HOME; $M2_HOME/bin/mvn "$@"
