#!/bin/bash
if [ -z "$1" ] ; then
        echo "使用方法：$0 新版本号"
        exit 1
fi
pushd $(dirname $0)
sed -i "s/%define openssh_ver.*/%define openssh_ver $1/g" openssh.spec
sed -i "s/%define openssh_rel.*/%define openssh_rel 1/g" openssh.spec
popd
