Name:           perl-Hash-Diff
Version:        0.005
Release:        6%{?dist}
Summary:        Return difference between two hashes as a hash
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Hash-Diff/
Source0:        http://search.cpan.org/CPAN/authors/id/B/BO/BOLAV/Hash-Diff-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Hash::Merge)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::use::ok)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Requires:       perl(Test::use::ok)

%{?perl_default_filter}

%description
Hash::Diff returns the difference between two hashes as a hash.

%prep
%setup -q -n Hash-Diff-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check


%files
%doc README
%{perl_vendorlib}/Hash/Diff.pm
%{_mandir}/man3/Hash::Diff.3pm*

%changelog
* Wed Dec 12 2012 Liu Di <liudidi@gmail.com> - 0.005-6
- 为 Magic 3.0 重建

* Sun Jan 29 2012 Liu Di <liudidi@gmail.com> - 0.005-5
- 为 Magic 3.0 重建

* Fri Jan 13 2012 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 0.005-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_17_Mass_Rebuild

* Thu Sep 15 2011 Emmanuel Seyman <emmanuel.seyman@club-internet.fr> - 0.005-3
- Fix typo in summary. (#614249)

* Thu Aug 11 2011 Emmanuel Seyman <emmanuel.seyman@club-internet.fr> - 0.005-2
- Clean up spec file.

* Sat Oct 9 2010 Jerome Fenal <jfenal@free.fr> 0.005-1
- Rebase on upstream, which fixes only typos in pod.
* Sat Sep 11 2010 Jerome Fenal <jfenal@free.fr> 0.003-2
- Bump release number to overcome rpm generation issues for review ??
* Wed Jul 14 2010 Jerome Fenal <jfenal@free.fr> 0.003-1
- Specfile autogenerated by cpanspec 1.78.
- Modified Requires and BuildRequires from perl(ok) to perl(Test::use::ok)
- added perl_default_filter
- Remove unnecessary Hash::Merge Require
- Fixed typo in description (from original Description pod)
- Removed directories from spec manifest, as there are other Hash::
  modules already packaged.
