#!/bin/bash
if [ -z "$1" ] ; then
        echo "使用方法：$0 新版本号"
        exit 1
fi
pushd $(dirname $0)
NAME=$(basename $(pwd))
sed -i "s/Version:.*/Version:\t$1/g" $NAME.spec
sed -i "s/Release:.*/Release:\t1%{?dist}/g" $NAME.spec
sed -i "s/rpmver .*/rpmver $1/g" $NAME.spec
popd
