#!/bin/bash
url="http://download.qt.io/official_releases/qt/"
new1='\/">'
new2='\/<'
downcommand="wget -q" 
pushd $(dirname $0) > /dev/null
if ! [ x"$UPDATEMAJOR" = x"" ]; then
	rm -f index.html && $downcommand $url -O index.html
	if [ -f index.html ];then
		newver1=`grep "$new1.*$new2" index.html |head -n 1| sed "s/.*$new1//" | sed "s/$new2.*//" | sed 's/^[ ]\{1,\}//;s/[ ]\{1,\}$//g'| cut -d">" -f 2`
	else
		echo "不能正常取得新版本号"
		exit 1
	fi
else
	specver=`rpmspec -q --qf "%{version}\n" qt5-qtconnectivity.spec |head -n 1`
	newver1=$(echo $specver | cut -d"." -f1).$(echo $specver | cut -d"." -f2)
fi	
rm -f index.html
url1="$url$newver1/"
$downcommand $url1 -O index.html
new3='\/">'
new4='\/<'
if [ -f index.html ];then
	newver=`grep "$new3.*$new4" index.html |head -n 1| sed "s/.*$new3//" | sed "s/$new4.*//" | sed 's/^[ ]\{1,\}//;s/[ ]\{1,\}$//g'`
	echo $newver
else
        echo "不能正常取得新版本号"
        exit 1
fi
rm -f index.html
popd > /dev/null
