#!/bin/bash
if [ -z "$1" ] ; then
        echo "使用方法：$0 新版本号"
        exit 1
fi
pushd $(dirname $0)
sed -i "s/Version:.*/Version: $1/g" xorg-x11-util-macros.spec
sed -i "s/Release:.*/Release: 0%{?dist}/g" xorg-x11-util-macros.spec
popd
