#!/bin/bash
if [ -z "$1" ] ; then
        echo "使用方法：$0 新版本号"
        exit 1
fi
pushd $(dirname $0)
MAJOR=`echo $1|cut -f1 -d"."`
MINOR=`echo $1|cut -f2 -d"."`
MICRO=`echo $1|cut -f3 -d"."`
sed -i "s/%define majorversion.*/%define majorversion $MAJOR/g" abiword.spec
sed -i "s/%define minorversion.*/%define minorversion $MINOR/g" abiword.spec
sed -i "s/%define microversion.*/%define microversion $MICRO/g" abiword.spec
sed -i "s/Release:.*/Release: 0%{?dist}/g" abiword.spec
popd
