Name:           perl-Bio-ASN1-EntrezGene
Version:	1.70
Release:	2%{?dist}
Epoch:		1
Summary:        Regular expression-based Perl Parser for NCBI Entrez Gene
Summary(zh_CN.UTF-8): 基于正则表达式的 NCBI Entrez Gene 的 Perl 解析器
License:        GPL+ or Artistic
Group:          Development/Libraries
Group(zh_CN.UTF-8): 开发/库
URL:            http://search.cpan.org/dist/Bio-ASN1-EntrezGene/
Source0:        http://search.cpan.org/CPAN/authors/id/C/CJ/CJFIELDS/Bio-ASN1-EntrezGene-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Bio::ASN1::EntrezGene is a regular expression-based Perl Parser for NCBI
Entrez Gene genome databases
(http://www.ncbi.nih.gov/entrez/query.fcgi?db=gene). It parses an ASN.1-
formatted Entrez Gene record and returns a data structure that contains all
data items from the gene record.

%description -l zh_CN.UTF-8
基于正则表达式的 NCBI Entrez Gene 的 Perl 解析器。

%prep
%setup -q -n Bio-ASN1-EntrezGene-%{version}

# remove all execute bits from the doc stuff
# so that dependency generator doesn't try to fulfill deps
find examples -type f -exec chmod -x {} 2>/dev/null ';'

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*
magic_rpm_clean.sh

## disable tests because of circular BuildRequires with bioperl
%check
%{?_with_check: || :}

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc examples
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Apr 24 2015 Liu Di <liudidi@gmail.com> - 1:1.70-2
- 为 Magic 3.0 重建

* Fri Apr 24 2015 Liu Di <liudidi@gmail.com> - 1.70-1
- 更新到 1.70

* Fri Jun 13 2014 Liu Di <liudidi@gmail.com> - 1.091-18
- 为 Magic 3.0 重建

* Thu Jun 12 2014 Liu Di <liudidi@gmail.com> - 1.091-17
- 为 Magic 3.0 重建

* Wed Dec 12 2012 Liu Di <liudidi@gmail.com> - 1.091-16
- 为 Magic 3.0 重建

* Sat Jan 28 2012 Liu Di <liudidi@gmail.com> - 1.091-15
- 为 Magic 3.0 重建

* Fri Jan 13 2012 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 1.091-14
- Rebuilt for https://fedoraproject.org/wiki/Fedora_17_Mass_Rebuild

* Wed Jun 15 2011 Marcela Mašláňová <mmaslano@redhat.com> - 1.091-13
- Perl mass rebuild

* Tue Feb 08 2011 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 1.091-12
- Rebuilt for https://fedoraproject.org/wiki/Fedora_15_Mass_Rebuild

* Wed Dec 15 2010 Marcela Maslanova <mmaslano@redhat.com> - 1.091-11
- 661697 rebuild for fixing problems with vendorach/lib

* Thu Apr 29 2010 Marcela Maslanova <mmaslano@redhat.com> - 1.091-10
- Mass rebuild with perl-5.12.0

* Mon Dec  7 2009 Stepan Kasal <skasal@redhat.com> - 1.091-9
- rebuild against perl 5.10.1

* Sat Jul 25 2009 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 1.091-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_12_Mass_Rebuild

* Thu Feb 26 2009 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 1.091-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_11_Mass_Rebuild

* Thu Mar 06 2008 Tom "spot" Callaway <tcallawa@redhat.com> - 1.091-6
Rebuild for new perl

* Tue Mar 04 2008 Tom "spot" Callaway <tcallawa@redhat.com> 1.091-5
- rebuild for new perl

* Tue Sep 04 2007 Alex Lancaster <alexl@users.sourceforge.net> 1.091-4
- Clarified license terms: GPL+ or Artistic

* Mon Apr 15 2007 Alex Lancaster <alexl@users.sourceforge.net> 1.091-3
- Bump for rebuild now that perl-bioperl is in the repo, which fulfills
  the Requires for this package.

* Mon Apr 02 2007 Alex Lancaster <alexl@users.sourceforge.net> 1.091-2
- Include the "examples" subdirectory as documentation as per comments
  from Chris Weyl.  Strip executable bits from these scripts.

* Fri Mar 23 2007 Alex Lancaster <alexl@users.sourceforge.net> 1.091-1
- Disable tests because of circular BuildRequires with perl-bioperl.
- Specfile autogenerated by cpanspec 1.69.1.
