#!/bin/bash
pushd $(dirname $0) > /dev/null
NAME=$(basename $(pwd)|sed -e 's/perl-//')
url="http://search.cpan.org/dist/$NAME/"
new1="$NAME-"
new2=".tar.gz"
downcommand="wget -q" 
rm -f index.html && $downcommand "$url" -O index.html
if [ -f index.html ];then
	newver=`grep "$new1.*$new2" index.html|grep -v latest|head -n 1| sed "s/.*$new1//" | sed "s/$new2.*//" | sed 's/^[ ]\{1,\}//;s/[ ]\{1,\}$//g'`
	if [ "$newver"x = "0.[0-9][0-9]"x ] ; then
		echo $newver
	else
		echo ${newver:0:4}.${newver:4:2}
	fi
else
	echo "不能正常取得新版本号"
	exit 1
fi
rm -f index.html
popd > /dev/null
