#!/bin/bash
url="http://dl.lm-sensors.org/lm-sensors/releases/?C=M;O=D"
new1="lm_sensors-"
new2=".tar.bz2"
downcommand="wget -q" 
pushd $(dirname $0) > /dev/null
rm -f ver.html && $downcommand "$url" -O ver.html
if [ -f ver.html ];then
	newver=`grep "$new1.*$new2" ver.html|head -n 1| sed "s/.*$new1//" | sed "s/$new2.*//" | sed 's/^[ ]\{1,\}//;s/[ ]\{1,\}$//g'`
	echo $newver
else
	echo "不能正常取得新版本号"
	exit 1
fi
rm -f ver.html
popd > /dev/null
