#!/bin/bash
if [ -z "$1" ] ; then
        echo "使用方法：$0 新版本号"
        exit 1
fi
pushd $(dirname $0)
main_ver=$(echo $1|cut -d"a" -f1|sed -e 's/.$//g')
min_ver=a$(echo $1|cut -d"a" -f2)
sed -i "s/%define main_ver.*/%define main_ver $main_ver/g" cdrtools.spec
sed -i "s/%define min_ver.*/%define min_ver $min_ver/g" cdrtools.spec
popd
