#!/bin/bash
if [ -z "$1" ] ; then
        echo "使用方法：$0 新版本号"
        exit 1
fi
pushd $(dirname $0)
#DATE=$(date -d '-1 day' +%Y-%m-%d)
DATE=$(date +%Y-%m-%d)
sed -i "s/%define date.*/%define date $DATE/g" mplayer.spec
sed -i "s/Release:.*/Release: 1%{?dist}/g" mplayer.spec
#这个地方的处理方法不是太好，需要改进
cp make_mplayer-ffmpeg_git_package.sh ~/rpmbuild/SOURCES
cd ~/rpmbuild/SOURCES
wget http://www.mplayerhq.hu/MPlayer/releases/mplayer-export-snapshot.tar.bz2
./make_mplayer-ffmpeg_git_package.sh
cd -
popd
