#!/bin/bash
url="http://www.geany.org/"
new1="Latest version is: "
new2=""
downcommand="wget -q" 
pushd $(dirname $0) > /dev/null
rm -f index.html && $downcommand "$url" -O index.html
if [ -f index.html ];then
	newver=`grep "$new1" index.html|head -n 1| sed "s/.*$new1//" `
	echo $newver
else
	echo "不能正常取得新版本号"
	exit 1
fi
rm -f index.html
popd > /dev/null
